### ISSUE TITLE
Statistiken

### ISSUE THREAD

**Issue by kremer-io** [schul-cloud/superhero-dashboard#21]
Wie mit @jprberlin besprochen, möchten wir das Superhero-Dashboard um die folgenden Statistiken erweitern:

- Anzahl Schulen, Klassen und Kurse
- Anzahl Lehrer und Schüler
- Anzahl angelegte / fertige Aufgaben
- Anzahl Themen, ggf. nach Kursen gruppiert
- Anzahl Dateien

@Langleu Hättest du eine Idee bzgl. Visualisierung?

Weitere Ideen:

- Anzeige von Piwik Daten (iFrame wäre hier die schnellste Art, ggf. über APIs)

**Comment by Langleu** [comment]
würde es ähnlich machen wie bei openHPI, da es alles nur single values sind lohnen sich Graphen nicht.

**Comment by kremer-io** [comment]
Stimmt, sollte im ersten Schritt denke ich auch reichen

**Comment by Langleu** [comment]
![image](https://user-images.githubusercontent.com/9141483/32890331-a093162e-cace-11e7-881f-d0d6488ce029.png)
das wären jetzt Mal alle single values die gefordert sind, welche über eine Route im Backend erreichbar wären, natürlich nur für super heroes :sunglasses: .
Falls die Frage aufkommt, wieso man nicht einfach direkt jede einzelne Route anspricht?
- Limit
Deshalb direkt über das Model die Collection ansprechen.

**Comment by jprberlin** [comment]
Nice. Can ich ein time stamp angeben um ein bestimmten tag abzufragen oder ist das immer aktuell? Dann müssten wir noch überlegen wo wir das sammeln um später Entwicklungen über die zeit darzustellen

**Comment by Langleu** [comment]
man könnte sich überlegen ob man noch einen DB Eintrag dahinter haut, also einmal fetchen für die aktuelle Situation und dann noch eine weitere Route wo man dann alle Einträge erhält die man bis dato gefetched hat oder cronjob 🤷‍♂️

On Thu, Nov 16, 2017 at 15:48, jprberlin <notifications@github.com> wrote:
Nice. Can ich ein time stamp angeben um ein bestimmten tag abzufragen oder ist das immer aktuell? Dann müssten wir noch überlegen wo wir das sammeln um später Entwicklungen über die zeit darzustellen

**Comment by jprberlin** [comment]
Fände ich cool

**Comment by jprberlin** [comment]
Ja fände ich cool.. wenn man das nicht über created at hinbekommt ...

**Comment by Langleu** [comment]
überlege mir da Mal was 👌

**Comment by pinussilvestrus** [comment]
Das bekommt man denke auf jeden fall über createdAt hin, man spricht ja eh direkt mit den Models ..

**Comment by Langleu** [comment]
zum Plotten würde man wahrscheinlich eh nur über nen find gehen und dann den Timestamp benutzen

**Comment by Langleu** [comment]
@jprberlin wenn die backend Routen drin sind, dann gibt es einmal die Single Values oder via CreatedAt von den jeweiligen Collections mit der Option als 2 Arrays x und y, fertig für Plot.ly.

![image](https://user-images.githubusercontent.com/9141483/32945687-ad8b8822-cb94-11e7-87ca-d6eb6a16fd62.png)

**Comment by jprberlin** [comment]
Bist ein Held :)
